// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {time} from '../models';

export function ClearCooldowns():Promise<void>;

export function GetCooldown():Promise<number>;

export function GetLastNotificationTime(arg1:string,arg2:string):Promise<time.Time>;

export function IsEnabled():Promise<boolean>;

export function Send(arg1:string,arg2:string):Promise<void>;

export function SendCritical(arg1:string,arg2:string):Promise<void>;

export function SendSummary(arg1:Array<string>):Promise<void>;

export function SetCooldown(arg1:number):Promise<void>;

export function SetEnabled(arg1:boolean):Promise<void>;

export function ShouldNotify(arg1:string,arg2:string):Promise<boolean>;
