// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearCooldowns() {
  return window['go']['backend']['NotificationManager']['ClearCooldowns']();
}

export function GetCooldown() {
  return window['go']['backend']['NotificationManager']['GetCooldown']();
}

export function GetLastNotificationTime(arg1, arg2) {
  return window['go']['backend']['NotificationManager']['GetLastNotificationTime'](arg1, arg2);
}

export function IsEnabled() {
  return window['go']['backend']['NotificationManager']['IsEnabled']();
}

export function Send(arg1, arg2) {
  return window['go']['backend']['NotificationManager']['Send'](arg1, arg2);
}

export function SendCritical(arg1, arg2) {
  return window['go']['backend']['NotificationManager']['SendCritical'](arg1, arg2);
}

export function SendSummary(arg1) {
  return window['go']['backend']['NotificationManager']['SendSummary'](arg1);
}

export function SetCooldown(arg1) {
  return window['go']['backend']['NotificationManager']['SetCooldown'](arg1);
}

export function SetEnabled(arg1) {
  return window['go']['backend']['NotificationManager']['SetEnabled'](arg1);
}

export function ShouldNotify(arg1, arg2) {
  return window['go']['backend']['NotificationManager']['ShouldNotify'](arg1, arg2);
}
