// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Send(arg1, arg2) {
  return window['go']['notifiactions']['NotificationManager']['Send'](arg1, arg2);
}

export function ShouldNotify(arg1) {
  return window['go']['notifiactions']['NotificationManager']['ShouldNotify'](arg1);
}
