// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddServer(arg1) {
  return window['go']['main']['App']['AddServer'](arg1);
}

export function ClearNotificationCooldowns() {
  return window['go']['main']['App']['ClearNotificationCooldowns']();
}

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function GetNotificationCooldown() {
  return window['go']['main']['App']['GetNotificationCooldown']();
}

export function GetNotificationsEnabled() {
  return window['go']['main']['App']['GetNotificationsEnabled']();
}

export function GetServers() {
  return window['go']['main']['App']['GetServers']();
}

export function GetSystemTheme() {
  return window['go']['main']['App']['GetSystemTheme']();
}

export function ManualCheck(arg1) {
  return window['go']['main']['App']['ManualCheck'](arg1);
}

export function SendDownServersSummary() {
  return window['go']['main']['App']['SendDownServersSummary']();
}

export function SetNotificationCooldown(arg1) {
  return window['go']['main']['App']['SetNotificationCooldown'](arg1);
}

export function SetNotificationsEnabled(arg1) {
  return window['go']['main']['App']['SetNotificationsEnabled'](arg1);
}

export function UpdateServer(arg1) {
  return window['go']['main']['App']['UpdateServer'](arg1);
}
