// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {backend} from '../models';

export function AddServer(arg1:main.Server):Promise<main.Server>;

export function ClearNotificationCooldowns():Promise<void>;

export function DeleteServer(arg1:string):Promise<void>;

export function GetNotificationCooldown():Promise<number>;

export function GetNotificationsEnabled():Promise<boolean>;

export function GetServers():Promise<Array<main.Server>>;

export function GetSettings():Promise<backend.Settings>;

export function GetSystemTheme():Promise<string>;

export function ManualCheck(arg1:main.Server):Promise<main.ServerStatus>;

export function SaveSettings(arg1:backend.Settings):Promise<void>;

export function SendDownServersSummary():Promise<void>;

export function SetNotificationCooldown(arg1:number):Promise<void>;

export function SetNotificationsEnabled(arg1:boolean):Promise<void>;

export function UpdateServer(arg1:main.Server):Promise<main.Server>;
