name: Build for Linux

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.24.3'

      - uses: actions/setup-node@v3
        with:
          node-version: '22.13.1'

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Build app
        run: wails build

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: wails-linux
          path: build/bin/*
