name: Build Wails App for Windows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.3' 

      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.13.1' 

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install
          npm run build

      - name: Build Wails App
        run: |
          wails build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wails-windows-build
          path: build/bin/*.exe
